### ISSUE TITLE
marker color error

### ISSUE THREAD

**Issue by TsumiNa** [joshpeng/Charcoal-Oceanic-Next#3]
Hello! With upgraded vscode to 1.13.0, file changed marker on the left bar became gray.

![2017-06-10 09 13 45 pm](https://user-images.githubusercontent.com/6410921/27002658-067f1872-4e22-11e7-8efb-ec691b2247ce.png)

**Comment by joshpeng** [comment]
The syntax tmTheme does not impact Visual Studio Code's skin theming.
