### ISSUE TITLE
Object key color should not match string color

### ISSUE THREAD

**Issue by nhuesmann** [joshpeng/Charcoal-Oceanic-Next#4]
Object keys are the same color as strings, making objects containing many string values hard to read. Example:

![screen shot 2018-05-18 at 2 19 39 pm](https://user-images.githubusercontent.com/613922/40258459-8b6f2aae-5aa6-11e8-9998-f8edb1cc1559.png)

I am using [Sublime-Babel-VSCode](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) with [Charcoal Oceanic Next](https://marketplace.visualstudio.com/items?itemName=joshpeng.theme-charcoal-oceanicnext). I wasn't sure if this was an issue with this extension or the other, so I'm going to leave this on both. Is there a workaround for this? Thanks!

**Comment by joshpeng** [comment]
You should be able to adjust it to your personal liking by adding a definition for the `string.unquoted.label` scope.

**Comment by nhuesmann** [comment]
@joshpeng Thanks, I was actually coming here to cancel this! I found out how to use the Inspect TS scopes tool in VSCode and got the scopes for strings and object properties. I'm all sorted!
